### ISSUE TITLE
latest sysbench 1.0.15: basic mysql driver failed

### ISSUE THREAD

**Issue by jlemc2009** [akopytov/sysbench#259]
./tpcc.lua --mysql-host=localhost --mysql-user=root --mysql-password=root --mysql-db=sbt --time=300 --threads=64 --report-interval=1 --tables=10 --scale=100  --db-driver=mysql prepare
sysbench 1.0.15 (using bundled LuaJIT 2.1.0-beta2)

Initializing worker threads...

FATAL: invalid database driver name: '\ufffd '
Segmentation fault (core dumped)

**Comment by akopytov** [comment]
I'm unable to reproduce it with exactly the same command in a CentOS 7 Docker container. What I need to investigate it further:

1. OS version
2. output of `ldd $(which sysbench)`
3. backtrace from the core dump.

**Comment by jlemc2009** [comment]
OS is Ubuntu 16.04, kernel 4.9.5

ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu10) 2.23

It looks like getservbyname() failed.

(gdb) bt
#0  0x00000000008bc5c0 in ?? ()
#1  0x00007ffff61153a0 in ?? () from /usr/lib/libnss_db.so.2
#2  0x00007ffff6115539 in ?? () from /usr/lib/libnss_db.so.2
#3  0x00007ffff611499a in ?? () from /usr/lib/libnss_db.so.2
#4  0x00007ffff6114ce2 in _nss_db_getservbyname_r () from /usr/lib/libnss_db.so.2
#5  0x00007ffff69d047a in __getservbyname_r (name=name@entry=0x7ffff790085b "mysql", 
    proto=proto@entry=0x7ffff787dc60 "tcp", resbuf=resbuf@entry=0x7ffff6c7c480 <resbuf>, 
    buffer=0x8baa40 "EMENT\"\n      else\n         id_def = \"INTEGER NOT NULL\"\n      end\n      engine_def = \"/*! ENGINE = \" .. sysbench.opt.mysql_storage_engine .. \" */\"\n      extra_table_options = mysql_table_options or \"\"\n"..., buflen=buflen@entry=1024, result=result@entry=0x7fffffffe398)
    at ../nss/getXXbyYY_r.c:266
#6  0x00007ffff69d0292 in getservbyname (name=0x7ffff790085b "mysql", proto=0x7ffff787dc60 "tcp")
    at ../nss/getXXbyYY.c:116
#7  0x00007ffff77eaf1b in mysql_server_init () from /usr/lib/x86_64-linux-gnu/libmysqlclient.so.20
#8  0x0000000000419c55 in mysql_drv_init () at drv_mysql.c:270
#9  0x000000000040da96 in db_create (name=<optimized out>) at db_driver.c:263
#10 0x0000000000437566 in lj_vm_ffi_call ()
#11 0x0000000000457716 in lj_ccall_func ()
#12 0x0000000000433446 in lj_cf_ffi_meta___call ()
#13 0x00000000004355c7 in lj_BC_FUNCC ()
#14 0x00000000004245dd in lua_pcall ()
#15 0x0000000000413623 in call_custom_command (L=0x40000378) at sb_lua.c:1494
#16 0x0000000000408e13 in main (argc=<optimized out>, argv=<optimized out>) at sysbench.c:1462

**Comment by elwood218** [comment]
What was the solution here?
