### ISSUE TITLE
working threads stuck at read(libpthread.so.0) after reconnected

### ISSUE THREAD

**Issue by ahdong2007** [akopytov/sysbench#465]
I use sysbench to test mysql.
intel x86 + centos 7.x
sysbench 1.1.0

command I used:
```
../sysbench oltp_read_write.lua --threads=${threadnum} --mysql-user=${user} --mysql-password="${pass}" --mysql-host=$host --mysql-port=$port --mysql-db=${db} --report-interval=1 --table-size=${table_size} --tables=${tablenum} --time=${timerun} --mysql-ignore-errors=all --thread-init-timeout=3 --debug=on --verbosity=5 run
```

if I reboot the mysql server, some times after reconnected, some of the working threads stuck at read(libpthread.so.0).

![image](https://user-images.githubusercontent.com/1320783/184503576-9735a073-73d2-4946-9b80-c1558cdbb6eb.png)

![image](https://user-images.githubusercontent.com/1320783/184503597-320a9a53-36b7-41bc-ba02-f20c57a42b7b.png)

pstack
```
Thread 12 (Thread 0x7f230d1c2700 (LWP 49456)):
#0  0x00007f230c99ce9d in nanosleep () from /lib64/libpthread.so.0
#1  0x000000000040a524 in sb_nanosleep (ns=<optimized out>) at sb_timer.h:102
#2  report_thread_proc (arg=<optimized out>) at sysbench.c:965
#3  0x00007f230c995ea5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f230b4b09fd in clone () from /lib64/libc.so.6
Thread 11 (Thread 0x7f230d160700 (LWP 49457)):
#0  0x00007f230c99c75d in read () from /lib64/libpthread.so.0
#1  0x00007f230cbf7df0 in vio_read () from /usr/lib64/mysql/libmysqlclient.so.18
#2  0x00007f230cbf7e71 in vio_read_buff () from /usr/lib64/mysql/libmysqlclient.so.18
#3  0x00007f230cbdbfba in my_real_read(st_net*, unsigned long*) () from /usr/lib64/mysql/libmysqlclient.so.18
#4  0x00007f230cbdce2c in my_net_read () from /usr/lib64/mysql/libmysqlclient.so.18
#5  0x00007f230cbcf84c in cli_safe_read () from /usr/lib64/mysql/libmysqlclient.so.18
#6  0x00007f230cbd0ebb in cli_read_query_result () from /usr/lib64/mysql/libmysqlclient.so.18
#7  0x00007f230cbcb52d in execute () from /usr/lib64/mysql/libmysqlclient.so.18
#8  0x00007f230cbcc049 in cli_stmt_execute () from /usr/lib64/mysql/libmysqlclient.so.18
#9  0x00007f230cbcd87a in mysql_stmt_execute () from /usr/lib64/mysql/libmysqlclient.so.18
#10 0x000000000041d15e in mysql_drv_execute (stmt=0x7f22fc009690, rs=0x7f22fc001188) at drv_mysql.c:875
#11 0x000000000040f096 in db_execute (stmt=0x7f22fc009690) at db_driver.c:488
#12 0x0000000027499e06 in ?? ()
#13 0x000f424000060ecb in ?? ()
#14 0x0000000000011000 in ?? ()
#15 0x00000000004140f0 in ?? () at sb_lua.c:1014
#16 0x0000000000000002 in ?? ()
#17 0x00007f230d0ee378 in ?? ()
#18 0x00007f230d0fa7f0 in ?? ()
#19 0x0000000000000000 in ?? ()
Thread 10 (Thread 0x7f230d12f700 (LWP 49458)):
#0  0x00007f230c99c75d in read () from /lib64/libpthread.so.0
#1  0x00007f230cbf7df0 in vio_read () from /usr/lib64/mysql/libmysqlclient.so.18
#2  0x00007f230cbf7e71 in vio_read_buff () from /usr/lib64/mysql/libmysqlclient.so.18
#3  0x00007f230cbdbfba in my_real_read(st_net*, unsigned long*) () from /usr/lib64/mysql/libmysqlclient.so.18
#4  0x00007f230cbdce2c in my_net_read () from /usr/lib64/mysql/libmysqlclient.so.18
#5  0x00007f230cbcf84c in cli_safe_read () from /usr/lib64/mysql/libmysqlclient.so.18
#6  0x00007f230cbcfd05 in cli_read_rows () from /usr/lib64/mysql/libmysqlclient.so.18
#7  0x00007f230cbcb941 in cli_read_prepare_result () from /usr/lib64/mysql/libmysqlclient.so.18
#8  0x00007f230cbcbc9d in mysql_stmt_prepare () from /usr/lib64/mysql/libmysqlclient.so.18
#9  0x000000000041c618 in mysql_drv_prepare (stmt=0x7f22d4008f00, query=0x7f2309bb5f80 "BEGIN", len=5) at drv_mysql.c:582
#10 0x000000000040ef93 in db_prepare (con=0x7f22d4000a10, query=0x7f2309bb5f80 "BEGIN", len=5) at db_driver.c:421
#11 0x0000000000434d61 in lj_vm_ffi_call ()
#12 0x000000000045af70 in lj_ccall_func ()
#13 0x0000000000430357 in lj_cf_ffi_meta___call ()
#14 0x0000000000432925 in lj_BC_FUNCC ()
#15 0x0000000000421472 in lua_pcall ()
#16 0x0000000000414138 in sb_lua_op_thread_run (thread_id=thread_id@entry=1) at sb_lua.c:435
#17 0x000000000040bc36 in worker_thread (arg=<optimized out>) at sysbench.c:834
#18 0x00007f230c995ea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007f230b4b09fd in clone () from /lib64/libc.so.6
Thread 9 (Thread 0x7f230d11e700 (LWP 49459)):
#0  0x00007f230c99c75d in read () from /lib64/libpthread.so.0
#1  0x00007f230cbf7df0 in vio_read () from /usr/lib64/mysql/libmysqlclient.so.18
#2  0x00007f230cbf7e71 in vio_read_buff () from /usr/lib64/mysql/libmysqlclient.so.18
#3  0x00007f230cbdbfba in my_real_read(st_net*, unsigned long*) () from /usr/lib64/mysql/libmysqlclient.so.18
#4  0x00007f230cbdce2c in my_net_read () from /usr/lib64/mysql/libmysqlclient.so.18
#5  0x00007f230cbcf84c in cli_safe_read () from /usr/lib64/mysql/libmysqlclient.so.18
#6  0x00007f230cbcfd05 in cli_read_rows () from /usr/lib64/mysql/libmysqlclient.so.18
#7  0x00007f230cbcb941 in cli_read_prepare_result () from /usr/lib64/mysql/libmysqlclient.so.18
#8  0x00007f230cbcbc9d in mysql_stmt_prepare () from /usr/lib64/mysql/libmysqlclient.so.18
#9  0x000000000041c618 in mysql_drv_prepare (stmt=0x7f22e0008f00, query=0x7f2309b95f80 "BEGIN", len=5) at drv_mysql.c:582
#10 0x000000000040ef93 in db_prepare (con=0x7f22e0000a10, query=0x7f2309b95f80 "BEGIN", len=5) at db_driver.c:421
#11 0x0000000000434d61 in lj_vm_ffi_call ()
#12 0x000000000045af70 in lj_ccall_func ()
#13 0x0000000000430357 in lj_cf_ffi_meta___call ()
#14 0x0000000000432925 in lj_BC_FUNCC ()
#15 0x0000000000421472 in lua_pcall ()
#16 0x0000000000414138 in sb_lua_op_thread_run (thread_id=thread_id@entry=2) at sb_lua.c:435
#17 0x000000000040bc36 in worker_thread (arg=<optimized out>) at sysbench.c:834
#18 0x00007f230c995ea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007f230b4b09fd in clone () from /lib64/libc.so.6
Thread 8 (Thread 0x7f230d0ed700 (LWP 49460)):
#0  0x00007f230c99c75d in read () from /lib64/libpthread.so.0
#1  0x00007f230cbf7df0 in vio_read () from /usr/lib64/mysql/libmysqlclient.so.18
#2  0x00007f230cbf7e71 in vio_read_buff () from /usr/lib64/mysql/libmysqlclient.so.18
#3  0x00007f230cbdbfba in my_real_read(st_net*, unsigned long*) () from /usr/lib64/mysql/libmysqlclient.so.18
#4  0x00007f230cbdce2c in my_net_read () from /usr/lib64/mysql/libmysqlclient.so.18
#5  0x00007f230cbcf84c in cli_safe_read () from /usr/lib64/mysql/libmysqlclient.so.18
#6  0x00007f230cbcfd05 in cli_read_rows () from /usr/lib64/mysql/libmysqlclient.so.18
#7  0x00007f230cbcb941 in cli_read_prepare_result () from /usr/lib64/mysql/libmysqlclient.so.18
#8  0x00007f230cbcbc9d in mysql_stmt_prepare () from /usr/lib64/mysql/libmysqlclient.so.18
#9  0x000000000041c618 in mysql_drv_prepare (stmt=0x7f22f401c030, query=0x7f2309b64f48 "BEGIN", len=5) at drv_mysql.c:582
#10 0x000000000040ef93 in db_prepare (con=0x7f22f4000a10, query=0x7f2309b64f48 "BEGIN", len=5) at db_driver.c:421
#11 0x0000000000434d61 in lj_vm_ffi_call ()
#12 0x000000000045af70 in lj_ccall_func ()
#13 0x0000000000430357 in lj_cf_ffi_meta___call ()
#14 0x0000000000432925 in lj_BC_FUNCC ()
#15 0x0000000000421472 in lua_pcall ()
#16 0x0000000000414138 in sb_lua_op_thread_run (thread_id=thread_id@entry=3) at sb_lua.c:435
#17 0x000000000040bc36 in worker_thread (arg=<optimized out>) at sysbench.c:834
#18 0x00007f230c995ea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007f230b4b09fd in clone () from /lib64/libc.so.6
Thread 7 (Thread 0x7f230d0dc700 (LWP 49461)):
#0  0x00007f230c99c75d in read () from /lib64/libpthread.so.0
#1  0x00007f230cbf7df0 in vio_read () from /usr/lib64/mysql/libmysqlclient.so.18
#2  0x00007f230cbf7e71 in vio_read_buff () from /usr/lib64/mysql/libmysqlclient.so.18
#3  0x00007f230cbdbfba in my_real_read(st_net*, unsigned long*) () from /usr/lib64/mysql/libmysqlclient.so.18
#4  0x00007f230cbdce2c in my_net_read () from /usr/lib64/mysql/libmysqlclient.so.18
#5  0x00007f230cbcf84c in cli_safe_read () from /usr/lib64/mysql/libmysqlclient.so.18
#6  0x00007f230cbcfd05 in cli_read_rows () from /usr/lib64/mysql/libmysqlclient.so.18
#7  0x00007f230cbcb941 in cli_read_prepare_result () from /usr/lib64/mysql/libmysqlclient.so.18
#8  0x00007f230cbcbc9d in mysql_stmt_prepare () from /usr/lib64/mysql/libmysqlclient.so.18
#9  0x000000000041c618 in mysql_drv_prepare (stmt=0x7f22f8008f00, query=0x7f2309b33f48 "BEGIN", len=5) at drv_mysql.c:582
#10 0x000000000040ef93 in db_prepare (con=0x7f22f8000a10, query=0x7f2309b33f48 "BEGIN", len=5) at db_driver.c:421
#11 0x0000000000434d61 in lj_vm_ffi_call ()
#12 0x000000000045af70 in lj_ccall_func ()
#13 0x0000000000430357 in lj_cf_ffi_meta___call ()
#14 0x0000000000432925 in lj_BC_FUNCC ()
#15 0x0000000000421472 in lua_pcall ()
#16 0x0000000000414138 in sb_lua_op_thread_run (thread_id=thread_id@entry=4) at sb_lua.c:435
#17 0x000000000040bc36 in worker_thread (arg=<optimized out>) at sysbench.c:834
#18 0x00007f230c995ea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007f230b4b09fd in clone () from /lib64/libc.so.6
Thread 6 (Thread 0x7f2309b7c700 (LWP 49462)):
#0  0x00007f230c99c75d in read () from /lib64/libpthread.so.0
#1  0x00007f230cbf7df0 in vio_read () from /usr/lib64/mysql/libmysqlclient.so.18
#2  0x00007f230cbf7e71 in vio_read_buff () from /usr/lib64/mysql/libmysqlclient.so.18
#3  0x00007f230cbdbfba in my_real_read(st_net*, unsigned long*) () from /usr/lib64/mysql/libmysqlclient.so.18
#4  0x00007f230cbdce2c in my_net_read () from /usr/lib64/mysql/libmysqlclient.so.18
#5  0x00007f230cbcf84c in cli_safe_read () from /usr/lib64/mysql/libmysqlclient.so.18
#6  0x00007f230cbcfd05 in cli_read_rows () from /usr/lib64/mysql/libmysqlclient.so.18
#7  0x00007f230cbcb941 in cli_read_prepare_result () from /usr/lib64/mysql/libmysqlclient.so.18
#8  0x00007f230cbcbc9d in mysql_stmt_prepare () from /usr/lib64/mysql/libmysqlclient.so.18
#9  0x000000000041c618 in mysql_drv_prepare (stmt=0x7f22ec008f00, query=0x7f2309b02f48 "BEGIN", len=5) at drv_mysql.c:582
#10 0x000000000040ef93 in db_prepare (con=0x7f22ec000a10, query=0x7f2309b02f48 "BEGIN", len=5) at db_driver.c:421
#11 0x0000000000434d61 in lj_vm_ffi_call ()
#12 0x000000000045af70 in lj_ccall_func ()
#13 0x0000000000430357 in lj_cf_ffi_meta___call ()
#14 0x0000000000432925 in lj_BC_FUNCC ()
#15 0x0000000000421472 in lua_pcall ()
#16 0x0000000000414138 in sb_lua_op_thread_run (thread_id=thread_id@entry=5) at sb_lua.c:435
#17 0x000000000040bc36 in worker_thread (arg=<optimized out>) at sysbench.c:834
#18 0x00007f230c995ea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007f230b4b09fd in clone () from /lib64/libc.so.6
Thread 5 (Thread 0x7f2309b4b700 (LWP 49463)):
#0  0x00007f230c99c75d in read () from /lib64/libpthread.so.0
#1  0x00007f230cbf7df0 in vio_read () from /usr/lib64/mysql/libmysqlclient.so.18
#2  0x00007f230cbf7e71 in vio_read_buff () from /usr/lib64/mysql/libmysqlclient.so.18
#3  0x00007f230cbdbfba in my_real_read(st_net*, unsigned long*) () from /usr/lib64/mysql/libmysqlclient.so.18
#4  0x00007f230cbdce2c in my_net_read () from /usr/lib64/mysql/libmysqlclient.so.18
#5  0x00007f230cbcf84c in cli_safe_read () from /usr/lib64/mysql/libmysqlclient.so.18
#6  0x00007f230cbcfd05 in cli_read_rows () from /usr/lib64/mysql/libmysqlclient.so.18
#7  0x00007f230cbcb941 in cli_read_prepare_result () from /usr/lib64/mysql/libmysqlclient.so.18
#8  0x00007f230cbcbc9d in mysql_stmt_prepare () from /usr/lib64/mysql/libmysqlclient.so.18
#9  0x000000000041c618 in mysql_drv_prepare (stmt=0x7f22f0008f00, query=0x7f2309ae2f48 "BEGIN", len=5) at drv_mysql.c:582
#10 0x000000000040ef93 in db_prepare (con=0x7f22f0000a10, query=0x7f2309ae2f48 "BEGIN", len=5) at db_driver.c:421
#11 0x0000000000434d61 in lj_vm_ffi_call ()
#12 0x000000000045af70 in lj_ccall_func ()
#13 0x0000000000430357 in lj_cf_ffi_meta___call ()
#14 0x0000000000432925 in lj_BC_FUNCC ()
#15 0x0000000000421472 in lua_pcall ()
#16 0x0000000000414138 in sb_lua_op_thread_run (thread_id=thread_id@entry=6) at sb_lua.c:435
#17 0x000000000040bc36 in worker_thread (arg=<optimized out>) at sysbench.c:834
#18 0x00007f230c995ea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007f230b4b09fd in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7f2309b1a700 (LWP 49464)):
#0  0x00007f230c99c75d in read () from /lib64/libpthread.so.0
#1  0x00007f230cbf7df0 in vio_read () from /usr/lib64/mysql/libmysqlclient.so.18
#2  0x00007f230cbf7e71 in vio_read_buff () from /usr/lib64/mysql/libmysqlclient.so.18
#3  0x00007f230cbdbfba in my_real_read(st_net*, unsigned long*) () from /usr/lib64/mysql/libmysqlclient.so.18
#4  0x00007f230cbdce2c in my_net_read () from /usr/lib64/mysql/libmysqlclient.so.18
#5  0x00007f230cbcf84c in cli_safe_read () from /usr/lib64/mysql/libmysqlclient.so.18
#6  0x00007f230cbcfd05 in cli_read_rows () from /usr/lib64/mysql/libmysqlclient.so.18
#7  0x00007f230cbcb941 in cli_read_prepare_result () from /usr/lib64/mysql/libmysqlclient.so.18
#8  0x00007f230cbcbc9d in mysql_stmt_prepare () from /usr/lib64/mysql/libmysqlclient.so.18
#9  0x000000000041c618 in mysql_drv_prepare (stmt=0x7f22e8008f00, query=0x7f2309ab1f48 "BEGIN", len=5) at drv_mysql.c:582
#10 0x000000000040ef93 in db_prepare (con=0x7f22e8000a10, query=0x7f2309ab1f48 "BEGIN", len=5) at db_driver.c:421
#11 0x0000000000434d61 in lj_vm_ffi_call ()
#12 0x000000000045af70 in lj_ccall_func ()
#13 0x0000000000430357 in lj_cf_ffi_meta___call ()
#14 0x0000000000432925 in lj_BC_FUNCC ()
#15 0x0000000000421472 in lua_pcall ()
#16 0x0000000000414138 in sb_lua_op_thread_run (thread_id=thread_id@entry=7) at sb_lua.c:435
#17 0x000000000040bc36 in worker_thread (arg=<optimized out>) at sysbench.c:834
#18 0x00007f230c995ea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007f230b4b09fd in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f2309ac9700 (LWP 49465)):
#0  0x00007f230c99c75d in read () from /lib64/libpthread.so.0
#1  0x00007f230cbf7df0 in vio_read () from /usr/lib64/mysql/libmysqlclient.so.18
#2  0x00007f230cbf7e71 in vio_read_buff () from /usr/lib64/mysql/libmysqlclient.so.18
#3  0x00007f230cbdbfba in my_real_read(st_net*, unsigned long*) () from /usr/lib64/mysql/libmysqlclient.so.18
#4  0x00007f230cbdce2c in my_net_read () from /usr/lib64/mysql/libmysqlclient.so.18
#5  0x00007f230cbcf84c in cli_safe_read () from /usr/lib64/mysql/libmysqlclient.so.18
#6  0x00007f230cbcfd05 in cli_read_rows () from /usr/lib64/mysql/libmysqlclient.so.18
#7  0x00007f230cbcb941 in cli_read_prepare_result () from /usr/lib64/mysql/libmysqlclient.so.18
#8  0x00007f230cbcbc9d in mysql_stmt_prepare () from /usr/lib64/mysql/libmysqlclient.so.18
#9  0x000000000041c618 in mysql_drv_prepare (stmt=0x7f22dc008f00, query=0x7f2309a80f48 "BEGIN", len=5) at drv_mysql.c:582
#10 0x000000000040ef93 in db_prepare (con=0x7f22dc000a10, query=0x7f2309a80f48 "BEGIN", len=5) at db_driver.c:421
#11 0x0000000000434d61 in lj_vm_ffi_call ()
#12 0x000000000045af70 in lj_ccall_func ()
#13 0x0000000000430357 in lj_cf_ffi_meta___call ()
#14 0x0000000000432925 in lj_BC_FUNCC ()
#15 0x0000000000421472 in lua_pcall ()
#16 0x0000000000414138 in sb_lua_op_thread_run (thread_id=thread_id@entry=8) at sb_lua.c:435
#17 0x000000000040bc36 in worker_thread (arg=<optimized out>) at sysbench.c:834
#18 0x00007f230c995ea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007f230b4b09fd in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f2309a98700 (LWP 49466)):
#0  0x00007f230c99c75d in read () from /lib64/libpthread.so.0
#1  0x00007f230cbf7df0 in vio_read () from /usr/lib64/mysql/libmysqlclient.so.18
#2  0x00007f230cbf7e71 in vio_read_buff () from /usr/lib64/mysql/libmysqlclient.so.18
#3  0x00007f230cbdbfba in my_real_read(st_net*, unsigned long*) () from /usr/lib64/mysql/libmysqlclient.so.18
#4  0x00007f230cbdce2c in my_net_read () from /usr/lib64/mysql/libmysqlclient.so.18
#5  0x00007f230cbcf84c in cli_safe_read () from /usr/lib64/mysql/libmysqlclient.so.18
#6  0x00007f230cbcfd05 in cli_read_rows () from /usr/lib64/mysql/libmysqlclient.so.18
#7  0x00007f230cbcb941 in cli_read_prepare_result () from /usr/lib64/mysql/libmysqlclient.so.18
#8  0x00007f230cbcbc9d in mysql_stmt_prepare () from /usr/lib64/mysql/libmysqlclient.so.18
#9  0x000000000041c618 in mysql_drv_prepare (stmt=0x7f22e4008f00, query=0x7f2309a60f80 "BEGIN", len=5) at drv_mysql.c:582
#10 0x000000000040ef93 in db_prepare (con=0x7f22e4000a10, query=0x7f2309a60f80 "BEGIN", len=5) at db_driver.c:421
#11 0x0000000000434d61 in lj_vm_ffi_call ()
#12 0x000000000045af70 in lj_ccall_func ()
#13 0x0000000000430357 in lj_cf_ffi_meta___call ()
#14 0x0000000000432925 in lj_BC_FUNCC ()
#15 0x0000000000421472 in lua_pcall ()
#16 0x0000000000414138 in sb_lua_op_thread_run (thread_id=thread_id@entry=9) at sb_lua.c:435
#17 0x000000000040bc36 in worker_thread (arg=<optimized out>) at sysbench.c:834
#18 0x00007f230c995ea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007f230b4b09fd in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f230d1a3940 (LWP 49454)):
#0  0x00007f230c997017 in pthread_join () from /lib64/libpthread.so.0
#1  0x00000000004139b9 in sb_thread_join (retval=0x0, thread=<optimized out>) at sb_thread.c:146
#2  sb_thread_join_workers () at sb_thread.c:192
#3  0x0000000000409937 in run_test (test=0x8a8740 <sbtest>) at sysbench.c:1201
#4  main (argc=<optimized out>, argv=<optimized out>) at sysbench.c:1577
```

**Comment by ahdong2007** [comment]
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/1320783/184503873-e06c0bba-1c10-4dd1-9f0c-f56feb64c033.png">
